[package]
name = "orecc-front"
version = "0.1.0"
edition = "2021"

[features]
xid = ["dep:unicode-ident"]

[dependencies]
lazy-regex = { version = "3.0.1" }
unicode-ident = { version = "1.0.11", optional = true }
codespan-reporting = "0.11.1"
